version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=notes_db
      - JWT_SECRET=abcd1234
      - JWT_EXPIRATION=24h
    depends_on:
      - postgres
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  api_node_modules: 